Traceback (most recent call last):
  File "/home/mikhail/Desktop/Learning/python/test.py", line 4, in <module>
    raise Exception('Exception message')
Exception: Exception message
